
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: Upen@1988
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
   
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: UserService
eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
     