server:
  port: 8081
spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: Upen@1988
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
   
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import: configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-59401106.okta.com/oauth2/default
          
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credential
            scope: internal
            client-id: 0oaj836zz44PgTa8m5d7
            client-secret: 5mWKL6FvCARQuWBbl2JWuEtXqTMWZjdbOoZlg5OWYU6Z49HFyp8nyQk0UFD_jd3M
            
        provider:
          okta:
            issuer-uri: https://dev-59401106.okta.com/oauth2/default
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: ALWAYS
      
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 50
        failure-rate-threshold: 5
        minimum-number-of-calls: 6
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 2s
        
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s
        
okta:
  oauth2:
    issuer: https://dev-59401106.okta.com/oauth2/default
    audience: api://default
      

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

#      
     